AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - config/*.rb
    - config/**/*.rb
    - db/*.rb
    - db/**/*.rb
    - bin/*
    - Gemfile
    - spec/*.rb
Metrics/LineLength:
  Max: 120
Metrics/BlockLength:
  CountComments: false
  Max: 25
  Exclude:
    - 'spec/**/*.rb'
    - 'spec/**/**/*.rb'
    - 'Gemfile'
Metrics/MethodLength:
  Max: 20
Style/AsciiComments:
  Enabled: false
Style/VariableNumber:
  Enabled: false
Style/NumericPredicate:
  EnforcedStyle: comparison
Style/PredicateName:
  Enabled: false
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: aligned
  Enabled: false
Layout/SpaceAroundOperators:
  Enabled: false
Layout/ExtraSpacing:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/ConditionalAssignment:
  Enabled: false
Documentation:
  Enabled: false
Metrics/ClassLength:
  Max: 300